### ISSUE TITLE
GHCR Docker image for linux/amd64 is not available

### ISSUE THREAD

**Issue by cdzombak** [boinkor-net/tsnsrv#48]
I haven't had a chance to dig into fixing this myself, but leaving a note here:

https://github.com/boinkor-net/tsnsrv/pkgs/container/tsnsrv lists images for linux/arm64 and unknown/unknown, but not linux/amd64.

I see references to linux/amd64 in the GitHub Actions workflow definition, so I'm guessing this is unintentional and is the result of some bug in the workflow definition.

**Comment by antifuchs** [comment]
Aaah oh grump. Sorry for the trouble, I haven't been using the images (and it shows!) - I'll investigate why they aren't tagged correctly.

**Comment by antifuchs** [comment]
Seems this was caused by the docker build/push workflow using matrix builds: Whichever platform finished first (usually linux/amd64 but on occasion, linux/arm64) would be the one available, plus a "mystery" unknown/unknown platform.

With #52, the workflow no longer uses matrix builds, which causes 3 platforms to be available on https://github.com/boinkor-net/tsnsrv/pkgs/container/tsnsrv/131290297?tag=main: `linux/amd64`, `linux/arm64` and `unknown/unknown` (and I have _not a single_ idea why ghcr thinks that unknown/unknown is a platform that exists or should be available).
